### ISSUE TITLE
doc error:upstream_ssl_verify default value is not false

### ISSUE THREAD

**Issue by wmzy** [ledgetech/ledge#173]
As the code [upstream_ssl_verify](https://github.com/pintsized/ledge#upstream_ssl_verify) default value is `true`:
https://github.com/pintsized/ledge/blob/4f72cd6929d5c9b02e296780aa0fddfe7acd087b/lib/ledge.lua#L68

**Comment by pintsized** [comment]
Thanks, fixed on master.
