### ISSUE TITLE
Openresty can't start: no file '/usr/local/lib/lua/5.1/ledge.so'

### ISSUE THREAD

**Issue by BrewToR** [ledgetech/ledge#175]
Hi there,

I'm confused. After being installed all the components (openresty, luarocks, ledge and prerequisites) here are the logs.
Nginx.conf has the minimal configuration which is in the project Readme (I just added the upstream)

`systemctl status openresty.service
● openresty.service - full-fledged web platform
   Loaded: loaded (/lib/systemd/system/openresty.service; enabled)
   Active: failed (Result: exit-code) since Thu 2018-06-07 14:00:05 CEST; 6min ago
  Process: 14085 ExecStop=/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 --pidfile /usr/local/openresty/nginx/logs/nginx.pid (code=exited, status=0/SUCCESS)
  Process: 14044 ExecStart=/usr/local/openresty/nginx/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 14088 ExecStartPre=/usr/local/openresty/nginx/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
 Main PID: 14046 (code=exited, status=0/SUCCESS)

Jun 07 14:00:05 golden2 nginx[14088]: no file '/usr/local/lib/lua/5.1/ledge.so'
Jun 07 14:00:05 golden2 nginx[14088]: no file '/usr/local/openresty/luajit/lib/lua/5.1/ledge.so'
Jun 07 14:00:05 golden2 nginx[14088]: no file '/usr/local/lib/lua/5.1/loadall.so'
Jun 07 14:00:05 golden2 nginx[14088]: stack traceback:
Jun 07 14:00:05 golden2 nginx[14088]: [C]: in function 'require'
Jun 07 14:00:05 golden2 nginx[14088]: init_by_lua:2: in main chunk
Jun 07 14:00:05 golden2 systemd[1]: openresty.service: control process exited, code=exited status=1
Jun 07 14:00:05 golden2 systemd[1]: Failed to start full-fledged web platform.
Jun 07 14:00:05 golden2 systemd[1]: Unit openresty.service entered failed state.
Jun 07 14:00:05 golden2 nginx[14088]: nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed`

FYI/BTW : I get openresty starts with this vhost [Vhost] (https://groups.google.com/d/msg/openresty-en/DaR_S8_H_0E/n4ailHHGAQAJ)

Thank you a lot for your help
ToR

**Comment by pintsized** [comment]
Apologies for the very very slow reply. This looks like a misconfigured `lua_package_path`. It's not finding the ledge module for some reason. `ledge.so` is not a thing, but Lua is trying all the options it has available to find a module called `ledge`. Further up your logs you will see it looking (and failing) for `ledge.lua`. In short, check your package path.
